# Generated by Django 3.0.8 on 2020-07-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_periods',
            field=models.ManyToManyField(blank=True, to='activeLog.activity_periods'),
        ),
    ]
